pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: node
            image: node:16-alpine3.12
            command:
            - cat
            tty: true
        '''
    }
  }
  stages {
    stage('Run migrations') {
      steps {
        container('maven') {
          sh "yarn typeorm migration:run"
        }
      }
    }
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'yarn test'
        }
      }
    }
  }
}