pipeline {
  agent any

  stages {
    stage('Docker Build Image') {
      steps {
        script {
          sh "docker build -t sam20fonsa1098/ticketing-auth auth/"
        }
      }
    }

    stage('Docker Push Image') {
      steps {
        withDockerRegistry([ credentialsId: "docker-hub-credentials", url: "" ]) {
          sh "docker push sam20fonsa1098/ticketing-auth"
        }
      }
    }
  }
}