name: auth_tests

on:
  push:
    paths:
      - 'auth/**'
    branches:
      - master
  pull_request:
    paths:
      - 'auth/**'
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && yarn install && yarn test:ci
  
