name: orders_test

on:
  push:
    paths:
      - 'orders/**'
    branches:
      - master
  pull_request:
    paths:
      - 'orders/**'
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && yarn install && yarn test:ci
